household_power_consumption <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", stringsAsFactors = FALSE)
household_power_consumption$Date = as.Date(household_power_consumption$Date, "%d/%m/%Y")
two_day_subset <- subset(household_power_consumption, household_power_consumption$Date == "2007-02-01" | household_power_consumption$Date == "2007-02-02")
rm(household_power_consumption)
two_day_subset$DateTime <- strptime(paste(two_day_subset$Date, two_day_subset$Time), format = "%Y-%m-%d %H:%M:%S", tz = "UTC")
two_day_subset$Global_active_power <- as.numeric(two_day_subset$Global_active_power)
png(filename = "plot4.png", width = 480, height = 480, units = "px", pointsize = 12, bg = "white")
par(mfrow = c(2,2))
plot(two_day_subset$DateTime, two_day_subset$Global_active_power, type = 'l', ylab="Global Active Power (kilowatts)", xlab = "")
plot(two_day_subset$DateTime, two_day_subset$Voltage, xlab = "datetime", ylab = "Voltage", type = "l")
plot(two_day_subset$DateTime, two_day_subset$Sub_metering_1, type = "l", xlab="", ylab = "Energy sub metering")
lines(two_day_subset$DateTime, two_day_subset$Sub_metering_2, col = "red")
lines(two_day_subset$DateTime, two_day_subset$Sub_metering_3, col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lwd = 1, col = c("black", "red", "blue"))
plot(two_day_subset$DateTime, two_day_subset$Global_reactive_power, xlab = "datetime", ylab = "Global Reactive Power", type = "l")
dev.off(dev.cur())