household_power_consumption <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", stringsAsFactors = FALSE)
household_power_consumption$DateTime <- strptime(paste(household_power_consumption$Date, household_power_consumption$Time), "%d/%m/%Y %H:%M:%S", tz = "UTC")
two_day_subset <- subset(household_power_consumption, household_power_consumption$DateTime >= "2007-01-31 23:59:59" & household_power_consumption$DateTime <= "2007-02-02 23:59")
rm(household_power_consumption)
two_day_subset$Global_active_power <- as.numeric(two_day_subset$Global_active_power)
png(filename = "plot1.png", width = 480, height = 480, units = "px", pointsize = 12, bg = "white")
hist(two_day_subset$Global_active_power, main = "Global Active Power", col = "red", xlab = "Global Active Power (kilowatts)")
dev.off(3)
