household_power_consumption <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", stringsAsFactors = FALSE)
#household_power_consumption$DateTime <- strptime(paste(household_power_consumption$Date, household_power_consumption$Time), "%d/%m/%Y %H:%M:%S", tz = "UTC")
household_power_consumption$Date = as.Date(household_power_consumption$Date, "%d/%m/%Y")
two_day_subset <- subset(household_power_consumption, household_power_consumption$Date == "2007-02-01" | household_power_consumption$Date == "2007-02-02")
rm(household_power_consumption)
two_day_subset$DateTime <- strptime(paste(two_day_subset$Date, two_day_subset$Time), format = "%Y-%m-%d %H:%M:%S", tz = "UTC")
two_day_subset$Global_active_power <- as.numeric(two_day_subset$Global_active_power)
png(filename = "plot2.png", width = 480, height = 480, units = "px", pointsize = 12, bg = "white")
plot(two_day_subset$DateTime, two_day_subset$Global_active_power, type = 'l', main = "Global Active Power vs Time of Day", ylab="Global Active Power (kilowatts)", xlab = "")
dev.off(dev.cur())